#!/bin/bash

# Function to display the design
display_design() {
    cat << "EOF"

  _____  _____    _   _                            _                        
 |_   _||  __ \  | \ | |                          | |                       
   | |  | |__) | |  \| |  ___    ___   _ __  __ _ | | _   _  ____ ___  _ __ 
   | |  |  ___/  | . ` | / _ \  / _ \ | '__|/ _` || || | | ||_  // _ \| '__|
  _| |_ | |      | |\  || (_) || (_) || |  | (_| || || |_| | / /|  __/| |   
 |_____||_|      |_| \_| \___/  \___/ |_|   \__,_||_| \__, |/___|\___||_|   
                                                       __/ |                
                                                      |___/                 

    By Noor Shaheed, Datto, Kaseya. 01/15/2024
AP RSSI and Transmit Power Checker
----------------------------
EOF
}

# Function to update and install tcpdump package
update_and_install_tcpdump() {
    echo "Updating packages..."
    opkg update
    echo "Installing tcpdump..."
    opkg install tcpdump
}

# Function to capture ARP packets with tcpdump for 30 seconds
capture_arp_packets() {
    echo "Capturing ARP packets for 30 seconds..."
    tcpdump -i eth0 -c 100 -w arp_packets.pcap arp
    echo "Capture completed."
}

# Main function
main() {
    display_design
    update_and_install_tcpdump
    capture_arp_packets
}

# Call the main function
main
