#!/bin/bash

# Function to display the design
display_design() {
    cat << "EOF"
 _                    _                                __                           _                        
| |_  ___  _ __    __| | _   _  _ __ ___   _ __     /\ \ \ ___    ___   _ __  __ _ | | _   _  ____ ___  _ __ 
| __|/ __|| '_ \  / _` || | | || '_ ` _ \ | '_ \   /  \/ // _ \  / _ \ | '__|/ _` || || | | ||_  // _ \| '__|
| |_| (__ | |_) || (_| || |_| || | | | | || |_) | / /\  /| (_) || (_) || |  | (_| || || |_| | / /|  __/| |   
 \__|\___|| .__/  \__,_| \__,_||_| |_| |_|| .__/  \_\ \/  \___/  \___/ |_|   \__,_||_| \__, |/___|\___||_|   
          |_|                             |_|                                          |___/                 


    By Noor Shaheed, Datto, Kaseya. 01/15/2024
auto tcpdump 
----------------------------
EOF
}

# Function to update and install tcpdump package
update_and_install_tcpdump() {
    echo "Updating packages..."
    opkg update
    echo "Installing tcpdump..."
    opkg install tcpdump
}

# Function to capture ARP packets with tcpdump for 30 seconds
capture_arp_packets() {
    echo "Capturing ARP packets for 30 seconds..."
    timeout 30 tcpdump -i eth0 | grep ARP
    echo "Capture completed."
}

# Main function
main() {
    display_design
    update_and_install_tcpdump
    capture_arp_packets
}

# Call the main function
main
